//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogRecord
    {
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public string FormName { get; set; }
        public string Task { get; set; }
        public Nullable<long> UsersID { get; set; }
        public Nullable<System.DateTime> LogDT { get; set; }
    }
}
